on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: [main]
    paths:
      - 'README.Rmd'

name: build-readme.yaml

permissions:
  contents: write

jobs:
  build-readme:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.release.target_commitish == 'main'
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'release' && github.event.release.target_commitish || github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.
          needs: readme

      - name: Install CmdStan
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)
          cmdstanr::install_cmdstan(cores = 2)
        shell: Rscript {0}

      - name: Build README
        run: |
          allcontributors::add_contributors(format = "text")
          rmarkdown::render("README.Rmd", output_format = "github_document")
          unlink("README.html")
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md README.Rmd man/figures/README-*.png
          git diff --staged --quiet || git commit -m "chore: update README [skip ci]"
          git push
